<?php 
	// Provincies BE
	$be = array(

	"antwerpen" => array(

		name 	=> 	"Antwerpen",
		title 	=> 	"Sexdate Antwerpen",
		info 	=>	"Antwerpen is de stad waar nog heel veel jonge 18 plus meiden geen leuke vriend hebben, er zijn ook meiden die voor de oudere man vallen omdat die vaak toch wel zorgzaam zijn. Deze single jonge vrouwen, hebben hun voorkeuren vastgelegd, dus stuur haar een berichtje om erachter te komen wat zei zoekt! Wil je toch iemand die wat ouder is? Dan ben je ook zeker op je plek bij Antwerpen, want ook daar zijn meiden die wel wat ouder zijn en vastheid zoeken!",
		tekst 	=> 	"<h2>Sexdating Antwerpen</h2><p>De drukke stad gewoon even meer dan beu? Of jij verveelt jezelf en weet niet te doen met jouw vrije tijd? Neem dan eens de tijd voor een chat bij sexdate met iemand uit de provincie Antwerpen. Meerdere mannen en vrouwen plaatsen een advertentie in de hoop snel een online sexdate te kunnen versieren. Boom, Deurne, Lier, het zijn maar een paar plekken waar verschillende vrouwen hun ondeugende gedachten verbergen. Wil je één van de Antwerpse dames een keer vurig verrassen? Verstuur één van hen, en spreek hen aan over hun voorkeur voor bijvoorbeeld tenen. Voor jij het weet bezorgen zij je een antwoord met een voorstel voor een zwoele chat terug. Of ben jij veelmeer het romantisch type dat het meer heeft voor een rustige babbel? Ook dit kan. Het aanbod in provincie Antwerpen is dan ook verassend uitgebreid. Aan jou de keus.</p><h3>Sexdate Antwerpen - Vrouw zoekt man</h3><p>Antwerpen, het vinden van een seksdate door de duizenden mensen die in Antwerpen zijn is de kans op een heerlijke seksdate daar ook zo makkelijk te realiseren. Bij 18Date hebben wij dan ook aandacht hierop gericht, waardoor het voor u nog eenvoudiger is om een lekkere seksdate te vinden in Antwerpen. Makkelijk en vlug zie je alle dames die veel goesting hebben in seks. Dus wacht niet en meld je gelijk aan en start je sexdate avontuur in Antwerpen.</p><h3>Neuken in Antwerpen</h3><p>Neuken in Antwerpen is zoals in iedere andere plaats heerlijk. Nochtans zijn er wel enkele verschillen en dit heeft vooral te maken met de vrouwen die er zijn. De meeste van hen zijn bloedgeil, zien geregeld verrukkelijke kerels passeren maar krijgen niet de kans om met hen te neuken. Daarom zijn de dames die zich op deze pagina hebben ingeschreven aan het zoeken naar een snelle, sexy date. Ze komen seks te kort en jij mag dit voor hen oplossen. Pas dus maar op dat jij niet te veel dames tegelijk aanschrijft, dan zou je het nog wel eens superdruk kunnen krijgen.</p>",
		img 	=>	"antwerpen"
		),
	"brussel" => array(

		name 	=> 	"Brussels",
		title 	=> 	"Sexdate Brussel",
		info 	=>	"Brussel is een studentenstad zoals de meeste al weten, daar vind je heel veel single 18 plus dames die nog geen relatie of vriendje hebben, gewoonweg omdat ze naast hun studie geen tijd hebben om een vriendje te vinden. Zij hebben zich ingeschreven op deze site om zo toch in contact te komen met een leuke man of vriend. Zoek jij haar eventjes op? Stuur haar een berichtje en laat weten dat je echt interesse toont, alleen zo ben je zeker dat jouw date geslaagd zal zijn.",
		tekst 	=> 	"<h2>Sexdating Brussel</h2><p>Brussel is een mooie maar zeer drukke regio. Door alle haast en stress die de mensen ervaren zijn ze ook hard toe aan ontspanning en ontlading. Hoe beter en lekkerder dan het beleven van een lekkere erotische seksdate?</p><h3>Sexdate Brussel - Vrouw zoekt man</h3><p>Heerlijk met elkaar in bad als voorspel, elkaar lekker inzepen, strelen en zoenen. Vervolgens elkaar zacht en teder afdrogen om samen vol geilheid op het bed te ploffen en elkaar stuk te neuken omdat jij daar al uren naar zocht. Waarom zou je niet even vlug contact leggen met de knapste vrouwen uit Brussel? Het registreren en de eerste chats zijn gratis en totaal vrijblijvend.</p><h3>Hotel sexdates zijn het beste in Brussel</h3><p>In het mooie Brussel vind je tientallen meerdere hotels. Deze zijn natuurlijk bij uitstek geschikt om jouw sexy afspraakje mee naar toe te nemen. Je kunt in de hotelkamers heerlijk anoniem met elkaar genieten van de heerlijkste seks.</p>",
		img 	=>	"brussel"
		),
	"henegouwen" => array(

		name 	=> 	"Henegouwen",
		title 	=> 	"Sexdate Henegouwen",
		info 	=>	"Als het gaat om wat gezelligheid en de meeste vrijgezellen? Moet je toch wel in Henegouwen zijn, want daar zijn zoveel 18 plus vrouwen die het heel gezellig vinden om eens op stap te gaan en niet alleen maar thuis achter de geraniums willen zitten. Wil je jouw dame meenemen naar de gezelligste stad van Henegouwen? Vraag haar vanavond nog mee!",
		tekst 	=> 	"",
		img 	=>	"henegouwen"
		),
	"limburg" => array(

		name 	=> 	"Limburg",
		title 	=> 	"Sexdate Limburg",
		info 	=>	"Van alle single 18 plus dames zijn er in Limburg de meeste echt single, deze zitten niet allemaal te wachten op een serieuze lange relatie omdat ze nog jong zijn en nog naar school gaan, wil jij gewoon een leuke date of een spannende beleven? Dan kan je verzekerd zijn met een van deze single 18 plus dames, want deze dames zijn allemaal nog vrijgezel! Als je te lang wacht, ben je jouw kans verkeken, want ze blijven niet stil zitten!",
		tekst 	=> 	"<h2>Sexdating Limburg België</h2><p>Je bent perfect gelukkig in jouw relatie, maar je wilt soms ook eens een andere gesprekspartner? Of je vindt dag in, dag uit kijken op dezelfde dame ook niet bijzonder interessant? Verschillende mannen en vrouwen uit de omgeving Limburg ervaren net datzelfde gevoel. Dat terwijl dames uit Limburg doorsnee vurige types zijn. Of je nu op zoek bent naar een loutere one-night-stand flirt, of langdurige passionele sexdating vriend, het kan allemaal. Niet slechts dames uit Hasselt, Gek of Sint-Truiden zijn vrij voor een sex date, ook mannen uit Tongeren en Maaseik willen echt niks liever dan met je in contact komen. Waar aarzel je nog over? Je droomman of droomvrouw is vermoedelijk vandaag online voor een geile sexdate chatsessie.</p><h3>Sexdate in Limburg - Vrouw zoekt man</h3><p>Het vinden van een sexdate in Limburg, België is nu nog eenvoudiger gemaakt dan waar dan ook. Op onze site 18Date zorgen we dat elke provincie veel kandidaten heeft om de kans op slagen zo hoog mogelijk te houden op onze datingplatform.</p><h3>Je versiert een Limburgse sexdate voor je het weet!</h3><p>Daardoor is het ook makkelijk om via de site een sexdate op te zoeken. De website is makkelijk in gebruik, zonder verplichting en gratis om te bezoeken en in te schrijven en je krijgt zelfs nog wat credits als geschenk als je je in hebt geschreven. Zo willen wij voor jou de mogelijkheid zo groot mogelijk maken op een succesvolle sexdate! Begin nu en vind je seksdate in Limburg België door op een vrouw naar keuze te klikken en jezelf gratis aan te melden.</p>",
		img 	=>	"limburg"
		),
	"luik" => array(

		name 	=> 	"Luik",
		title 	=> 	"Sexdate Luik",
		info 	=>	"In Luik is het heel gezellig, maar wist je ook dat er heel veel knappe 18 plus dames zijn die nog geen vriendje aan hun zijde hebben? Deze jonge dames vallen vaak voor een wat oudere man omdat die toch wel serieuzer zijn. De 18 plus dames, willen gewoon eens meegenomen worden op een leuke date, sex komt absoluut niet op de eerste plaats en dat moet voor jou ook belangrijk zijn! Stuur haar nu een berichtje, nu ze online is!",
		tekst 	=> 	"<h2>Sexdating Luik</h2><p>In de mooiste provincie van België, Luik zijn ook de heerlijkste meiden. Deze meiden zijn gemakkelijk, vrij en hard op zoek naar een geile date.</p><h3>Sexdate in Luik - Vrouw zoekt man</h3><p>Kies dan uit de dames de vrouw die jou het meeste bevalt, meld je gratis aan en verstuur haar een opwindend en origineel eerste berichtje. Als jij haar een verrassend complimentje maakt kun je er zeker van zijn dat ze een leuke en wellicht zelfs wel geile reactie aan je terugstuurt. Wanneer je het beginnetje eenmaal gemaakt hebt, is de stap naar een echte opwindende sexdate niet zo heel groot meer. Is Doggystyle je lievelingsstandje? Dan moet je op deze website zeker even gaan antwoorden!</p><h3>Doggystyle in Luik?</h3><p>De vrouwen uit de provincie Luik zitten het liefst op hun handen en knieën. Dat heeft niets te maken met het feit dat de dames hier wat passiever zijn maar meer met het gegeven dat ze graag diep en hard geneukt worden. Die Luikse meiden en vrouwen nemen hem graag diep, hard en lang in hun sappige poesje.</p>",
		img 	=>	"luik"
		),
	"luxemburg" => array(

		name 	=> 	"Luxemburg",
		title 	=> 	"Sexdate Luxemburg",
		info 	=>	"Oei oei oei, wist je dat in Luxemburg nog teveel 18 plus singles zijn die helemaal niet aan een vriendje kunnen komen door hun drukke studie? Ze hebben in de avond vaak wel tijd voor een leuke date, maar kunnen helemaal geen leuke single mannen vinden. Help jij deze jonge dames aan de avond van hun dromen? Stuur haar dan gauw een berichtje!",
		tekst 	=> 	"<h2>Sexdating Luxemburg</h2><p>Luxemburg in België staat bekend om de geweldige bergen en vooral de rustige natuur die je er kunt bewonderen. Maar wat vele mensen niet weten is dat dit ook de regio is waar de meerderheid van de spannende sexdates plaats vinden.</p><h3>Sexdate in Luxemburg - Vrouw zoekt man</h3><p>Net als al aangegeven vinden er heel veel opwindende afspraakjes plaats in Luxemburg. Waarom zou jij daar niet eens lekker van profiteren en je op deze website gelijk inschrijven? Zodra jij deze vrouwen en meiden leert kennen zou je willen dat je hen eerder had gevonden. Zo hitsig en gewillig vind je ze nergens anders. Regel vandaag je sexdate via 18Date en neuk deze avond nog zo’n lekkere gewillige vrouw!</p>",
		img 	=>	"luxemburg"
		),
	"namen" => array(

		name 	=> 	"Namen",
		title 	=> 	"Sexdate Namen",
		info 	=>	"Voor de allerleukste single 18 plus dames moet je echt naar Namen komen, hele leuke en gewillige jonge dames die nog allemaal single zijn en wachten op hun heerlijke date. Deze dames willen niet alleen een vriendje voor het leven, zijn ook in voor een spannende sex date, neem jij jouw 18 plus dame mee naar de bioscoop voor een stiekem avontuurtje? Stuur haar dan snel een berichtje!",
		tekst 	=> 	"<h2>Sexdating Namen</h2><p>In Namen zijn er genoeg gezellige en voornamelijk sexy plekken om eens verrukkelijk te genieten met je sexdate. Je vindt er tal van carpoolplekken waar vrouwen graag eens willen daten om lekker te gaan neuken met een kerel die daar ook wel zin in heeft.</p><h3>Sexdate in Namen - Vrouw zoekt man</h3><p>Het vinden van een goede partner om die spannende sexdate mee te hebben? Nu je toch op de pagina bent zou je een account kunnen inschrijven en een van de profielen een keer mogen bekijken. Al deze heren en dames zijn opzoek naar een super hete date op een carpoolplaats. Discreet, stiekem en vrij. Meld je zonder verplichting en kosteloos aan, zoek de perfecte dame uit en spreek hem/haar een keer aan!</p><h3>Carpoolplekken in de provincie Namen</h3><p>De carpoolplaatsen die je in de provincie Namen vindt zijn bij uitstek geschikt om een keer spannende seks te hebben. Lekker geilen in de auto of in de bosjes achter of naast de parkeerplaatsen. Veel heren en dames hebben de wens om het een keer in de auto te doen op een geile plaats als een carpoollocatie. Waarom zou je dat niet in Namen willen doen? De carpoolplekken lenen zich daar prima voor, tal van mensen zien deze vorm van sexdaten wel zitten maar wat maakt het moeilijk?</p>",
		img 	=>	"namen"
		),
	"oost-vlaanderen" => array(

		name 	=> 	"Oost-Vlaanderen",
		title 	=> 	"Sexdate Oost-Vlaanderen",
		info 	=>	"Voor een super spannende date met een jonge meid vanaf 18 jaar, moet je zeker in Oost-Vlaanderen zijn, daar zijn zoveel knappe meiden die nog geen vriendje hebben. Er zijn er zeker die te porren zijn voor een spannende date en absoluut geen relatie zoeken, maar meer willen dan alleen gezellig een drankje samen doen. Als je jouw meid hebt gevonden, stuur haar dan snel een lief berichtje!",
		tekst 	=> 	"<h2>Sexdating Oost-Vlaanderen</h2><p>Oost-Vlaanderen is nog steeds één van de verstedelijkte gebieden in België. Dat feit weerspiegelt zich ook in het assortiment aan nationaliteiten. Aziatisch, Arabisch, Latino of gewoon Westers, elk van hen hebben ze interesse in een sex date. En je wil maar vast deze diversiteit ontdekken? Meerdere heren en dames uit Oost-Vlaanderen willen niks liever dan met jou een heet gesprek hebben over jouw sensuele gedachten en geheime fantasieën. Of jij daarbij nou een voorkeur hebt voor lingerie, zweet, pijn, profielen uit Oost-Vlaanderen willen ze maar al te graag met jou bespreken. Ben jij met andere woorden aan het zoeken naar een sexdate contact uit Aalst, Gent of Sint-Niklaas? Dan is deze pagina je beginplek om te gaan zoeken.</p><h3>Sexdate in Oost-Vlaanderen - Vrouw zoekt man</h3><p>In Oost-Vlaanderen wonen erg veel single vrouwen die hard toe zijn aan een goede beurt. Waarom de concentratie in de provincie zo hoog is, weet niemand. Maar hou hier dus wel rekening mee. Ben je op zoek naar een sexdate en woon je in Oost-Vlaanderen, of ben je bereid hierheen te komen? Dan garanderen we je de lekkerste nachten van je leven.</p><h3>Zoek, chat, neuk!</h3><p>Het vinden van een sexdate in Oost-Vlaanderen gaat nu nog een stuk gemakkelijker nu we met een heel team hebben gezorgd dat iedereen gemakkelijk en sneller de beste date kan regelen. Via onze zoekfunctie kun je jouw voorkeuren opgeven, wij zoeken dan snel en veilig de beste matches voor jou. Neem contact op met een of verschillende vrouwen die je aanspreken, versier ze en spreek met ze af om te neuken. Breng het wel verstandig, niet iedereen is even blij met een directe aanpak. Registreren, opzoek gaan en zelfs de eerste 3 mails zijn helemaal gratis en vrijblijvend. Kan jij nog een reden bedenken om niet gelijk te beginnen? Geen idee, wij ook niet!</p>",
		img 	=>	"oost-vlaanderen"
		),
	"vlaams-brabant" => array(

		name 	=> 	"Vlaams-Brabant",
		title 	=> 	"Sexdate Vlaams-Brabant",
		info 	=>	"Voor eerlijke 18 plus dames moet je zeker eens rondkijken in Vlaams-Brabant, want alleen in Vlaams-Brabant ben je verzekerd van een eerlijke date met een van deze dames! Voor een gezellig dagje weg of gewoon ergens wat drinken? Dan zit je bij de jonge dames van Vlaams-Brabant op je plek, want deze dames wachten tot ze een berichtje van je krijgen! Laat jij je droom dame wachten?",
		tekst 	=> 	"<h2>Sexdating Vlaams-Brabant</h2><p>Op zoek naar een sexdate contact uit de omgeving Vlaams-Brabant? Kijk dan niet te ver. De zoekertjes bevatten misschien je ideale sexdating partner. Wil jij het speelse karakter van vrouwen uit Halle zien? Of ben je eerder aan het zoeken naar iemand uit Landen of Vilvoorde die zelf het initiatief neemt voor meer? Het kan allemaal. Het aanbod aan profielen uit Vlaams-Brabant is tenslotte zo divers. 18Date brengt gelijkgezinde mensen maar al te graag in contact met elkaar. Het leuke aan online sexdaten is dat je beslist wat er gebeurt. Reageren op een bericht, laten zien wat jij wil, sexdaten was nog nooit zo geil en vrijblijvend. Hoezo wacht je nog? Misschien is die ene heer of dame waar jij naar zoekt, nu aan het wachten op een online flirt.</p><h3>Sexdate in Vlaams-Brabant - Vrouw zoekt man </h3><p>Sexdaten in Vlaams-Brabant? Ja ook in Vlaams-Brabant zoeken elke dag vele mannen en vrouwen naar een heerlijk potje seks, door het grote aanbod van mensen die zich hebben aangemeld, hebben we ook op de website veel mogelijkheden om een keer heerlijk los te gaan. Hoezo zou je nog aarzelen?</p><h3>Vlaams-Brabant neuken?</h3><p>Vraag maar een keer aan de dames uit deze geweldige provincie hoe zij het liefste neuken. Het standje heeft niet echt een formele naam maar de dames hebben een absolute voorkeur! In andere provincies zijn heel veel dames erg terughoudend in het daten van een geile sexdate. De vrouwen in deze provincie doen niks liever dan neuken. Het liefste zouden ze je nu al ontmoeten. Heb jij tijd voor deze vrouwen?</p><h3>Neukdate in Vlaams-Brabant</h3><p>Het zal jou nog verbazen hoeveel dames er op de site open staan voor anale sex! Veel vrouwen kunnen daar net zo van genieten als doorsnee sex. Het geeft een extra dimensie, een pijnprikkel gedurende het neuken waardoor die gewillige Vlaams-Brabantse dames hier zo gek op zijn. Spreek een keer een aantal vrouwen aan en vraag ze er maar naar. Wedden dat ik gelijk heb?</p>",
		img 	=>	"vlaams-brabant"
		),
	"waals-brabant" => array(

		name 	=> 	"Waals-Brabant",
		title 	=> 	"Sexdate Waals-Brabant",
		info 	=>	"Voor een gezellige vrijgezelle dame van 18 plus, moet je zeker eens in Waals-Brabant rondkijken. Heb je al gezien hoeveel jonge dames nog single zijn? Nee? Nou zoek haar dan gauw even op en stuur haar een berichtje, want voor je het weet, gaat je buurman ermee vandoor! Jouw leuke date gevonden? Als je kijkt of ze online is, heb je kans dat je vanavond die date nog kan hebben!",
		tekst 	=> 	"<h2>Sexdating Waals-Brabant</h2><p>Vrouwen die zich heerlijk laten nemen door een spannende kerel in de buurt van Waals-Brabant het prachtige Belgische gebied waar elke dag duizenden mensen zoeken naar buitensex of gewoon een andere vorm van bloedgeile, spannende sex.</p><h3>Sexdate in Waals-Brabant - Vrouw zoekt man</h3><p>De allerlekkerste locaties voor heerlijk opwindende buitenseks in Waals-Brabant vind je rond: Waterloo, Nijvel, Roosbeek, Bevelkom, Thy, Waver, Eigenbrakel en Bevelkom. Maar ook om de andere steden en dorpen vind je veel mogelijkheden om de heetste buitensex dates te hebben. Wees wel verstandig, spreek eerst even af wat jij wel en niet wil doen, dan hou je gedurende je eerste ontmoeting extra tijd over om elkaar helemaal gek te maken.</p><h3>Buitensex in Waals-Brabant</h3><p>Of het aan het weer ligt of aan de vele steden om heerlijk te genieten van de heerlijkste buitensex weet niemand. Feit is dat er in Waals-Brabant meer buitensex fans zijn dan in elke andere regio dan ook. Deze regio in het geweldige België, leent zich daar ook uitstekend voor.</p>",
		img 	=>	"waals-brabant"
		),
	"west-vlaanderen" => array(

		name 	=> 	"West-Vlaanderen",
		title 	=> 	"Sexdate West-Vlaanderen",
		info 	=>	"Ben je op zoek naar een gezellige of spannende date met een 18 plus dame? Dan zit je in West-Vlaanderen goed, dat zijn namelijk heel veel jonge dames van 18 jaar en ouder die nog geen leuke date hebben gevonden en op zoek zijn naar een maatje om gezellige dingen mee te doen of eens op stap te gaan. Wil je jouw perfecte date laten slagen met de leukste dame uit West-Vlaanderen? Kijk dan gauw even op haar profiel en stuur haar een berichtje!",
		tekst 	=> 	"<h2>Sexdating West-Vlaanderen</h2><p>Opzoek zijn naar een passionele spontane sexdate is vaak niet makkelijk. Hoe weet je immers dat die heer of dame hetzelfde zoekt? Nochtans kan 18Date je bij die ontdekkingsreis helpen. Verschillende vrouwen en mannen uit omgeving West-Vlaanderen zijn net als jij op zoek naar een sex date. Wist je overigens dat dames uit Ieper of Brugge niet verlegen zijn voor een lapdance? Ook mannen uit West-Vlaanderen mogen verre van watjes genoemd worden. SM, bondage, het zijn enige voorbeelden van zaken waar bepaalde West-Vlaamse mannen mee overweg kunnen. Blijf dus niet bij de pakken zitten, en spreek nu één van de sexdate profielen uit West-Vlaanderen aan. Voor jij het weet ben je samen aan het genieten van een hete babbel of sex date.</p><h3>Sexdate in West-Vlaanderen - Vrouw zoekt man</h3><p>Sexdate in West-Vlaanderen? Door de vele aanmeldingen van grotendeels vrouwen die dagelijks op zoek zijn naar geile sexdates is het in die provincie een makkie om een pikante date te vinden! Aarzel niet te lang en bekijk direct via de profielen of er een gezellige geile vrouw voor jou bijzit waar jij wel een keer verrukkelijk los mee kan gaan.</p><h3>West-Vlaanderen, de pijp-regio?</h3><p>In West-Vlaanderen vind je de echte pijpkoninginnen van België! Deze vrouwen zijn zo gek op het geven van een pijpbeurt en orale seks. Heb jij al een keer een heerlijke opwindende pijpdate mee gemaakt? Nee? Dan moet je toch echt een keer rijden naar West-Vlaanderen! De gewillige vrouwen en meiden die hier zijn laten jou graag voelen waarom deze regio zo populair is bij mannen. En het vervelendste voor deze dames is dat er veel meer dames dan mannen zijn. Doe hiermee snel je voordeel voor iedereen dit gemerkt heeft en ga je gratis registreren!</p><p>Die dames vinden het geven van een blowjob niet zomaar voorspel, voor hen is het een levenswijze! Kies de spannendste vrouw met de geilste pijpmond uit de contacten en mogelijk heb jij vanavond al hoe het voelt om gepijpt te worden door een vrouw</p>",
		img 	=>	"west-vlaanderen"

		)
	);
?>